# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use Node.js LTS as the base image
FROM node:20-slim AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies (including dev dependencies for build)
RUN npm ci --ignore-scripts

# Copy source code
COPY . .

# Build the package
RUN npm run build

# Minimal image for runtime
FROM node:20-slim

# Set working directory
WORKDIR /app

# Copy built files
COPY --from=builder /app/bin ./bin
COPY --from=builder /app/build ./build
COPY --from=builder /app/scripts/notion-openapi.json ./scripts/
COPY --from=builder /app/package*.json ./

# Install only production dependencies
RUN npm ci --ignore-scripts --omit-dev

# Set default environment variables
ENV NOTION_API_VERSION="2022-06-28"
ENV PORT=3000
ENV NODE_ENV=production

# Expose port for remote connections
EXPOSE 3000

# Run remote server by default (for cloud deployments)
# For stdio mode (local), override with: docker run ... node bin/cli.mjs
CMD ["node", "build/scripts/start-remote-server.js"]
