services:
  # Stdio mode (for local MCP connections)
  notion-mcp-server-stdio:
    build: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_API_VERSION=${NOTION_API_VERSION:-2022-06-28}
      - BASE_URL=${BASE_URL:-https://api.notion.com}

  # Remote mode (for HTTP/SSE connections)
  notion-mcp-server-remote:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
    command: ["build/scripts/start-remote-server.js"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
